MHStoreBundle\Entity\Product:
    properties:
        price:
            - NotBlank: ~
            - Type: Integer
            - Range:
                min: 1
                max: 100000
                minMessage: Min 1 euros
                maxMessage: Max 100000 euros
        name:
            - NotBlank: ~
            - Type: String
        description:
            - NotBlank: ~
            - Type: String

MHStoreBundle\Entity\Credit:
    properties:
        number:
            - NotBlank: ~
            - Type: Integer
            - Range:
                min: 1
                max: 100000
                minMessage: Min 1 euros
                maxMessage: Max 100000 euros