MHStoreBundle\Entity\Product:
    properties:
        price:
            - NotBlank: ~
            - Type: Integer
            - Range:
                min: 1
                max: 100000
                minMessage: Min 1 euros
                maxMessage: Max 100000 euros
        name:
            - NotBlank: ~
            - Type: String
            - Length:
                min: 8
                max: 50
        description:
            - NotBlank: ~
            - Type: String
            - Length:
                min: 10
                max: 1000

MHStoreBundle\Entity\Credit:
    properties:
        number:
            - NotBlank: ~
            - Type: Integer
            - Range:
                min: 1
                max: 100000
                minMessage: Min 1 euros
                maxMessage: Max 100000 euros